<a href="https://colab.research.google.com/github/jerry-wrong/HTML_Test/blob/master/chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1A first look at a neural network

Listing 2.1 Loading the MNIST dataset in Keras

In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
!pwd

/content


In [9]:
PATH ='/content/drive/MyDrive/tensorflow'
%cd '/content/drive/MyDrive/tensorflow'

/content/drive/MyDrive/tensorflow


In [10]:
!pwd

/content/drive/MyDrive/tensorflow


Listing 2.2 The network architecture

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([ 
  layers.Dense(512, activation="relu"),
  layers.Dense(10, activation="softmax")
])
# 不用写输入层
# hidden layer
# output layer

Listing 2.3 The compilation step

In [ ]:
model.compile(optimizer="rmsprop", 
  loss="sparse_categorical_crossentropy",
  metrics=["accuracy"])

Listing 2.4 Preparing the image data

In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255 
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

Listing 2.5 “Fitting” the model

In [ ]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 8ms/step - loss: 0.2583 - accuracy: 0.9246
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.1052 - accuracy: 0.9690
Epoch 3/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0688 - accuracy: 0.9799
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0508 - accuracy: 0.9844
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0375 - accuracy: 0.9888


Listing 2.6 Using the model to make predictions

In [ ]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

array([1.6676195e-08, 2.0055585e-10, 9.0436589e-07, 4.5529618e-05,
       7.6719033e-14, 1.4304063e-08, 3.3224999e-14, 9.9995327e-01,
       8.9731735e-08, 1.8863231e-07], dtype=float32)

In [ ]:
predictions[0].argmax()

7

In [ ]:
predictions[0][7]

0.99995327

In [ ]:
predictions[0,7]

0.99995327

In [ ]:
test_labels[0]

7

Listing 2.7 Evaluating the model on new data

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 2ms/step - loss: 0.0754 - accuracy: 0.9774
test_acc: 0.977400004863739


# 2.2 Data representation for neural networks